# Generated by Django 4.0.2 on 2022-02-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=150)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
